### ISSUE TITLE
ERROR: 'str' object has no attribute 'content'

### ISSUE THREAD

**Issue by JeremyBickel** [FullStackRetrieval-com/RetrievalTutorials#4]
```
runnable = PROMPT | self.llm
new_chunk_summary = runnable.invoke({
    "proposition": proposition
}).content
```
ERROR: 'str' object has no attribute 'content'

Have you seen this before? I've tried to trace it, but it seems beyond me. What's the answer?! (TY)

**Comment by gkamradt** [comment]
This means that what is coming back from 

```
runnable.invoke({
    "proposition": proposition
})
```

is a string and doesn't have a content attribute. Remove the `.content` and it should work

**Comment by JeremyBickel** [comment]
@gkamradt  Ah. I wondered why runnable.invoke() returns a string and dug into langchain a lot. But I started over with the agentic chunker from here and changed as little as I could.. I'm using llama.cpp, so I suppose it has a different response format than OpenAI.
